version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ../envs/.utils.env
    networks:
      - sgrid-network
    ports:
      - "8080:80"

networks:
  sgrid-network:
    name: sgrid-network
    external: true
